services:
  tocka-interface:
    container_name: tocka-interface
    build:
      context: ../config/
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    volumes:
      - ../tocka:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - tocka-prometheus
      - tocka-alertmanager
    networks:
      - tocka-network

  tocka-api-alertmanager:
    build: ./api-alertmanager
    container_name: tocka-api-alertmanager
    ports:
      - "3000:3000"
    depends_on:
      - tocka-alertmanager
    volumes:
      - ../tocka:/app/tocka
    restart: unless-stopped
    networks:
      - tocka-network

  tocka-prometheus:
    image: prom/prometheus:latest
    container_name: tocka-prometheus
    ports:
      - 9090:9090
    volumes:
      - ../config/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    restart: unless-stopped
    networks:
      - tocka-network

  tocka-alertmanager:
    image: prom/alertmanager:latest
    container_name: tocka-alertmanager
    ports:
      - 9093:9093
    volumes:
      - ../config/alertmanager:/config
      - alertmanager-data:/data
    command: --config.file=/etc/alertmanager/alertmanager.yml --log.level=debug
    restart: unless-stopped
    networks:
      - tocka-network

  tocka-node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: tocka-node-exporter
    command:
      - --path.rootfs=/host
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run|boot|var/lib/docker/overlay2)($|/)
    ports:
      - 9100:9100
    volumes:
      - /:/host
    restart: unless-stopped
    networks:
      - tocka-network

volumes:
  prometheus-data:
    driver: local
  alertmanager-data:
    driver: local

networks:
  tocka-network:
    driver: bridge
