services:
  tocka-interface:
    container_name: tocka-interface
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    volumes:
      - ./tocka:/usr/share/nginx/html
    restart: unless-stopped
    depends_on:
      - tocka-api-zabbix
    networks:
      - tocka-network

  tocka-api-zabbix:
    build: ./api-zabbix
    container_name: tocka-api-zabbix
    ports:
      - "3333:3000"
    volumes:
      - ./tocka:/app/tocka
    restart: unless-stopped
    networks:
      - tocka-network

networks:
  tocka-network:
    driver: bridge
