services:
  tocka-interface:
    container_name: tocka-interface
    environment:
     API_URL: http://tocka-api-zabbix:3000/health
     POLL_INTERVAL: 10000
    build:
      context: ../
      dockerfile: tocka/Dockerfile
    ports:
      - "1234:80"
    volumes:
      - ../tocka:/app
    restart: unless-stopped
    depends_on:
      - tocka-api-zabbix
    networks:
      - tocka-network

  tocka-api-zabbix:
    build: ./api-zabbix
    container_name: tocka-api-zabbix
    environment:
      POLL_INTERVAL: 10000
      ZABBIX_URL: http://cratis-ubuntu-lab:7080/api_jsonrpc.php
      ZABBIX_TOKEN: 9e2260f1f68fee28b31074ce3f860edd8b7f0fde8b01505a0f0227429b0d9cc3
    ports:
      - "3000:3000"
    volumes:
      - ../tocka:/app/tocka
    restart: unless-stopped
    networks:
      - tocka-network

networks:
  tocka-network:
    driver: bridge