services:
  tocka-frontend:
    container_name: tocka-frontend
    environment:
      API_URL: http://tocka-api-zabbix:3000
      POLL_INTERVAL: 10000
      FRONTEND_PORT: 80
    build:
      context: ../
      dockerfile: config/Dockerfile
    image: tocka-frontend:latest
    ports:
      - "1234:80"
    restart: unless-stopped
    depends_on:
      - tocka-api-zabbix
    networks:
      - tocka-network

  tocka-api-zabbix:
    build: ./api-zabbix
    image: tocka-api-zabbix:latest
    container_name: tocka-api-zabbix
    environment:
      POLL_INTERVAL: 10000
      ZABBIX_URL: http://cratis-ubuntu-lab:7080/api_jsonrpc.php
      ZABBIX_TOKEN: 9e2260f1f68fee28b31074ce3f860edd8b7f0fde8b01505a0f0227429b0d9cc3
      ZABBIX_MODE: new
      ZABBIX_LOOKBACK_SECONDS: 604800
      API_PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - tocka-network

networks:
  tocka-network:
    driver: bridge