name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove old local images
        run: |
          docker image rm tocka-api-zabbix || true
          docker image rm tocka-api-alertmanager || true
          docker image rm tocka-frontend || true
          docker image rm dinop7283/tocka-monitoring-docker:api-zabbix || true
          docker image rm dinop7283/tocka-monitoring-docker:api-alertmanager || true
          docker image rm dinop7283/tocka-monitoring-docker:frontend || true
          docker image rm dinop7283/tocka-monitoring-docker || true

      - name: Build Docker Compose Images
        run: |
          docker compose build

      - name: Tag Docker Images
        run: |
          docker tag tocka-api-zabbix:latest dinop7283/tocka-monitoring-docker:api-zabbix
          docker tag tocka-api-alertmanager:latest dinop7283/tocka-monitoring-docker:api-alertmanager
          docker tag tocka-frontend:latest dinop7283/tocka-monitoring-docker:frontend

      - name: Push Docker Images to Docker Hub
        run: |
          docker push dinop7283/tocka-monitoring-docker:api-zabbix
          docker push dinop7283/tocka-monitoring-docker:api-alertmanager
          docker push dinop7283/tocka-monitoring-docker:frontend